import type { Metadata } from "next";
import { Geist_Mono, Mukta } from "next/font/google";
import "./globals.css";

const muktaSans = Mukta({
  weight: ["400", "500", "600"],
  variable: "--font-mukta-sans",
  subsets: ["latin-ext"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${muktaSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="mt-12 mx-auto w-fit text-gray-500 text-sm p-8">
          <a href="https://github.com/niyabits" target="_blank" rel="noreferrer" className="hover:text-gray-800 transition">
            crafted by <span className="underline underline-offset-6">@niyabits</span>
          </a>
        </footer>
      </body>
    </html>
  );
}
